### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by volcompt** [bradlucas/get-yahoo-quotes-python#1]
Hi there! Thank you for the code. I tried to use it but I keep getting this error:

Downloading AAPL to AAPL.csv
Traceback (most recent call last):
  File "get-yahoo-quotes.py", line 96, in <module>
    download_quotes(symbol)
  File "get-yahoo-quotes.py", line 83, in download_quotes
    cookie, crumb = get_cookie_crumb(symbol)
  File "get-yahoo-quotes.py", line 57, in get_cookie_crumb
    cookie, lines = get_page_data(symbol)
  File "get-yahoo-quotes.py", line 52, in get_page_data
    lines = r.content.strip().replace('}', '\n')
TypeError: a bytes-like object is required, not 'str'

Any idea on what's going on?

**Comment by bradlucas** [comment]
Hi, 
I retried my version here and it works so I'm wondering what the difference might be on your end.

- Are you cloning the repo and running the same?
- You have `requests` installed? Maybe you have a virtualenv and have the requests library installed

I suspect yes so the next thing I'd do would be to print out the results inside of get_page_data. Try printing r.content just after the r=requests.get(url) call. This should who the entire source of the requested page. You can also `print r` to get the status of the call. It should return `<Response [200]>`

Hope this helps. If not let me know.

- Brad

**Comment by leantengyew** [comment]
Hi Brad:

I have similar issue. I'm using Python 3.6. Is your code on Python 2.x.x ? I think this error only happens on Python 3.x.x. Probably it's due to the line 48. Do you have a similar script on Python 3.x.x? Thanks.

**Comment by bradlucas** [comment]
I did write the script using Python 2. I'll work on a Python 3 version and get back to you.

**Comment by bradlucas** [comment]
leantengyew, 

I've updated the repo with an updated `get-yahoo-quotes.py`. This new version is runnable under Python 2 and 3.

- Brad

**Comment by leantengyew** [comment]
Hi Brad:

Thanks mate! It works perfectly 👍 

Regards,
Adrian
